### ISSUE TITLE
Reasons for Configuration required page

### ISSUE THREAD

**Issue by ericfischerbav** [tkrebs/ep3-bs#453]
I'm trying to set up a docker image for the EP3 system.

I double checked the `config/autoload/local.php` several times, checked the connection to the db container through the apache container. The configured database exists and the connection is working.

However, I still get the page "Cofiguration required". What could be the reason for that besides a missing or false configuration?

**Comment by cbits68** [comment]
please also check /ep3-bs/data/cache/module-config-cache.ep3-bs.php
You also have to update database configuration here.
I just had the same issue after upgrading from mySQL 5.6 to 5.7. I only updated db configuration in local.php but forgot to do it for the cache ...

**Comment by ericfischerbav** [comment]
Thanks for the fast comment. As it's fresh installation within the docker container, there is not cache.

**Comment by cbits68** [comment]
please also have a look at [https://gitlab.kh-berlin.de/hheiss/ep3-bs-docker](url)
this is alrerady a docker based installation of ep3-bs by Holger Heißmeyer

**Comment by Shineson1001** [comment]
Hi @ericfischerbav.
i use this DockerFile and docker-compose.yml

**Dockerfile**
```
FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -yq --no-install-recommends \
    apt-utils \
    curl \
    git \
    locales \
    apache2 \
    libapache2-mod-php7.4 \
    php7.4-intl \
    php7.4-cli \
    php7.4-json \
    php7.4-curl \
    php7.4-fpm \
    php7.4-gd \
    php7.4-ldap \
    php7.4-mbstring \
    php7.4-mysql \
    php7.4-soap \
    php7.4-sqlite3 \
    php7.4-xml \
    php7.4-zip \
    php-imagick \
    mariadb-common \
    mariadb-client \
    iputils-ping \
    ca-certificates \
    composer\
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Set locales
RUN locale-gen en_US.UTF-8 en_GB.UTF-8 de_DE.UTF-8 es_ES.UTF-8 fr_FR.UTF-8 it_IT.UTF-8 km_KH sv_SE.UTF-8 fi_FI.UTF-8
RUN a2enmod rewrite
COPY 000-default.conf /etc/apache2/sites-available/

EXPOSE 80

WORKDIR /var/www/html
RUN rm ./index.html

RUN git clone https://github.com/tkrebs/ep3-bs.git /var/www/html
RUN mv ./config/init.php.dist ./config/init.php && rm ./public/.htaccess_original && rm ./config/autoload/local.php.dist

COPY local.php ./
COPY index.min.js ./
RUN mv ./local.php ./config/autoload/
RUN composer install --prefer-dist --no-scripts --no-dev --no-autoloader && rm -rf /root/.composer
RUN composer dump-autoload --no-scripts --no-dev --optimize
RUN chown -R www-data ./ && find ./ -type d -exec chmod 755 {} \; && find ./ -type f -exec chmod 644 {} \;

VOLUME [ "/var/www/html" ]
HEALTHCHECK --interval=5s --timeout=3s --retries=3 CMD curl -f http://localhost || exit 1
CMD apachectl -D FOREGROUND
```

docker build -t test/ep3:0.1 . --no-cache

**docker-compose.yml**
```
version: "3"

services:
  mariadb:
    image: mariadb:$MARIADB_TAG
    container_name: "${PROJECT_NAME}_mariadb"
    hostname: "$DB_HOST"
    stop_grace_period: 30s
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - mariadb-data:/var/lib/mysql

  apache:
    image: test/ep3:0.1
    container_name: "${PROJECT_NAME}_apache"
    hostname: 'ep3'
    environment:
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
    ports:
      - "8888:80/tcp"
    volumes:
      - apache-html:/var/www/html
    depends_on:
      - mariadb

volumes:
   apache-html:
     driver: local
   mariadb-data:
     driver: local
```

You also need this files:
**.env** 
```
PROJECT_NAME=ep3

DB_NAME=ep3
DB_USER=ep3dbusr
DB_PASSWORD=ep3dbusr
MYSQL_RANDOM_ROOT_PASSWORD=1
DB_HOST=mariadb

MARIADB_TAG=10.5.9
```

**000-default.conf** for your rewrite settings
**local.php**
```
<?php
/**
 * Local application configuration
 *
 * Insert your local database credentials here
 * and provide the email address the system should use.
 */

return array(
    'db' => array(
        'database' => getenv("DB_NAME"),
        'username' => getenv("DB_USER"),
        'password' => getenv("DB_PASSWORD"),

        'hostname' => getenv("DB_HOST"),
        'port' => null,
    ),
    'mail' => array(
        'type' => 'sendmail', // or 'smtp' or 'smtp-tls'
        'address' => 'info@bookings.example.com',

        'host' => '?', // for 'smtp' type only, otherwise remove or leave as is
        'user' => '?', // for 'smtp' type only, otherwise remove or leave as is
        'pw' => '?', // for 'smtp' type only, otherwise remove or leave as is

        'port' => 'auto', // for 'smtp' type only, otherwise remove or leave as is
        'auth' => 'plain', // for 'smtp' type only, change this to 'login' if you have problems with SMTP authentication
    ),
    'i18n' => array(
        'choice' => array(
            'en-US' => 'English',
            'de-DE' => 'Deutsch',

            // More possible languages:
            // 'fr-FR' => 'Français',
            // 'hu-HU' => 'Magyar',
        ),

        'currency' => 'EUR',

        // The language is usually detected from the user's web browser.
        // If it cannot be detected automatically and there is no cookie from a manual language selection,
        // the following locale will be used as the default "fallback":
        'locale' => 'de-DE',
    ),
);
```
